In [18]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.15.0-dev20190708'

In [3]:
tf.enable_eager_execution()

In [4]:
print(tf.reduce_sum([1, 2, 3]))

tf.Tensor(6, shape=(), dtype=int32)


In [5]:
print(tf.encode_base64("hello world"))


tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)


In [28]:
w = tf.Variable([[3.0]])
w.numpy()

array([[3.]], dtype=float32)

In [19]:
with tf.GradientTape() as tape:
  loss = tf.math.log(w * w)

loss

grad = tape.gradient(loss, w)
print(grad)  # => tf.Tensor([[ 2.]], shape=(1, 1), dtype=float32)

array([[3.]], dtype=float32)

In [29]:
a=5

In [31]:
tf.one_hot(a,depth=10).numpy()

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [32]:
help(tf.linalg)

W0709 14:50:09.774566 139701956855616 deprecation_wrapper.py:118] From /usr/lib/python3.6/inspect.py:342: The name tf.linalg.transpose is deprecated. Please use tf.linalg.matrix_transpose instead.



Help on package tensorflow._api.v1.linalg in tensorflow._api.v1:

NAME
    tensorflow._api.v1.linalg - Operations for linear algebra.

PACKAGE CONTENTS


FILE
    /home/abzooba/.local/lib/python3.6/site-packages/tensorflow_core/_api/v1/linalg/__init__.py


